# -*- coding: utf-8 -*-

"""
/***************************************************************************
 CounterpartStreams
                                 A QGIS plugin
 Conflation_DEM
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2021-03-30
        copyright            : (C) 2021 by Sokhrannykh V., Samsonov T.
        email                : vitaliy_mapgeo@mail.ru
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Sokhrannykh V., Samsonov T., Lomonosov MSU Faculty of Geography '
__date__ = '2021-03-30'
__copyright__ = '(C) 2021 by Sokhrannykh V., Samsonov T. '

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

from qgis.PyQt.QtCore import QCoreApplication
from qgis.core import (QgsProcessing,
                       QgsMessageLog,
                       QgsFeatureSink,
                       QgsProcessingException,
                       QgsProcessingAlgorithm,
                       QgsProcessingParameterField,
                       QgsProcessingParameterFileDestination,
                       QgsProcessingParameterRasterDestination,
                       QgsProcessingParameterNumber,
                       QgsProcessingParameterRasterLayer,
                       QgsProcessingParameterFeatureSource,
                       QgsProcessingParameterVectorLayer,
                       QgsProcessingParameterFeatureSink)

from .Conflation_DEM_by_Links_general import conflate_dem_by_links

class ConflateDemByLinks(QgsProcessingAlgorithm):
    INPUT_DEM = 'Input DEM'
    RIVERS = 'Input vector Rivers'
    INPUT_LINKS = 'Input conflation links'
    DIST_COUNT = 'Distance value for the buffer'
    FILTER_COUNT = 'Value for input filtering (increases operation speed but decreases accuracy)'
    OUTPUT_DEM = 'Output DEM'

    def initAlgorithm(self, config=None):
        """
        Here we define the inputs and output of the algorithm, along
        with some other properties.
        """

        # We add the input vector features source. It can have any kind of
        # geometry.

        self.addParameter(
            QgsProcessingParameterRasterLayer(
                self.INPUT_DEM,
                self.tr('Input DEM')
            )
        )

        self.addParameter(
            QgsProcessingParameterVectorLayer(
                self.INPUT_LINKS,
                self.tr('Input conflation links'),
                [QgsProcessing.TypeVectorAnyGeometry]
            )
        )
        self.addParameter(
            QgsProcessingParameterVectorLayer(
                self.RIVERS,
                self.tr('Input vector streams'),
                [QgsProcessing.TypeVectorAnyGeometry]
            )
        )
        self.addParameter(
            QgsProcessingParameterNumber(
                self.DIST_COUNT,
                self.tr('Distance value for the buffer'),
                defaultValue=5000
            )
        )

        self.addParameter(
            QgsProcessingParameterNumber(
                self.FILTER_COUNT,
                self.tr('Value for input filtering (increases operation speed but decreases accuracy)'),
                defaultValue=1
            )
        )

        self.addParameter(
            QgsProcessingParameterFileDestination(
                self.OUTPUT_DEM,
                self.tr('Output DEM')
            )
        )
        return

    def processAlgorithm(self, parameters, context, feedback):
        """
        Here is where the processing itself takes place.
        """
        dem_path = self.parameterAsRasterLayer(parameters, self.INPUT_DEM, context).dataProvider().dataSourceUri()
        rivers = self.parameterAsVectorLayer(parameters, self.RIVERS, context).dataProvider().dataSourceUri()
        links = self.parameterAsVectorLayer(parameters, self.INPUT_LINKS, context).dataProvider().dataSourceUri()
        distance = self.parameterAsDouble(parameters, self.DIST_COUNT, context)
        filter = self.parameterAsDouble(parameters, self.FILTER_COUNT, context)
        output_dem = self.parameterAsOutputLayer(parameters, self.OUTPUT_DEM, context)

        conflate_dem_by_links(dem_path, rivers, links, distance, filter, output_dem)

        return {self.OUTPUT_DEM: output_dem}

    def name(self):
        """
        Returns the algorithm name, used for identifying the algorithm. This
        string should be fixed for the algorithm, and must not be localised.
        The name should be unique within each provider. Names should contain
        lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'Conflate DEM by links'

    def displayName(self):
        """
        Returns the translated algorithm name, which should be used for any
        user-visible display of the algorithm name.
        """
        return self.tr(self.name())

    def group(self):
        """
        Returns the name of the group this algorithm belongs to. This string
        should be localised.
        """
        return self.tr(self.groupId())

    def groupId(self):
        """
        Returns the unique ID of the group this algorithm belongs to. This
        string should be fixed for the algorithm, and must not be localised.
        The group id should be unique within each provider. Group id should
        contain lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return ''

    def tr(self, string):
        return QCoreApplication.translate('Processing', string)

    def createInstance(self):
        return ConflateDemByLinks()
