# -*- coding: utf-8 -*-

"""
/***************************************************************************
 CounterpartStreams
                                 A QGIS plugin
 Conflation_DEM
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2021-03-30
        copyright            : (C) 2021 by Sokhrannykh V., Samsonov T. 
        email                : vitaliy_mapgeo@mail.ru
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Sokhrannykh V., Samsonov T., Lomonosov MSU Faculty of Geography '
__date__ = '2021-03-30'
__copyright__ = '(C) 2021 by Sokhrannykh V., Samsonov T. '

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

from qgis.PyQt.QtCore import QCoreApplication
from qgis.core import (QgsProcessing,
                       QgsMessageLog,
                       QgsFeatureSink,
                       QgsProcessingException,
                       QgsProcessingAlgorithm,
                       QgsProcessingParameterField,
                       QgsProcessingParameterFileDestination,
                       QgsProcessingParameterRasterDestination,
                       QgsProcessingParameterNumber,
                       QgsProcessingParameterRasterLayer,
                       QgsProcessingParameterFeatureSource,
                       QgsProcessingParameterVectorLayer,
                       QgsProcessingParameterFeatureSink)

from osgeo import gdal
import geopandas as gpd
import numpy as np
from .WBT.whitebox_tools import WhiteboxTools
from .Counterpart_Streams_general import counterpart_streams
from .ConflationLinks_general import conflation_links
import os


class CounterpartStreamsAlgorithm(QgsProcessingAlgorithm):
    """
    This is an example algorithm that takes a vector layer and
    creates a new identical one.

    It is meant to be used as an example of how to create your own
    algorithms and explain methods and variables used to do it. An
    algorithm like this will be available in all elements, and there
    is not need for additional work.

    All Processing algorithms should extend the QgsProcessingAlgorithm
    class.
    """

    # Constants used to refer to parameters and outputs. They will be
    # used when calling the algorithm from another algorithm, or when
    # calling from the QGIS console.


    INPUT = 'Input DEM'
    RIVERS = 'Input Vector Streams'
    FIELD = 'Streams Field ID'
    DIST = 'Buffer zone, m'
    COST_MASK = 'Cost raster mask for Streams'
    OUTPUT = 'Output Counterpart Streams'

    def initAlgorithm(self, config=None):
        """
        Here we define the inputs and output of the algorithm, along
        with some other properties.
        """

        # We add the input vector features source. It can have any kind of
        # geometry.
        self.addParameter(
            QgsProcessingParameterRasterLayer(
                self.INPUT,
                self.tr('Input DEM')
            )
        )

        self.addParameter(
            QgsProcessingParameterVectorLayer(
                self.RIVERS,
                self.tr('Input Streams vector layer'),
                [QgsProcessing.TypeVectorAnyGeometry]
            )
        )

        self.addParameter(
            QgsProcessingParameterField(
                self.FIELD,
                self.tr('Streams Field ID'),
                parentLayerParameterName = self.RIVERS
            )
        )

        self.addParameter(
            QgsProcessingParameterNumber(
                self.DIST,
                self.tr('Buffer zone, m'),
                type=QgsProcessingParameterNumber.Double,
                defaultValue=5000
            )
        )

        self.addParameter(
            QgsProcessingParameterNumber(
                self.COST_MASK,
                self.tr('Cost raster mask for Streams'),
                type=QgsProcessingParameterNumber.Double,
                defaultValue=40
            )
        )

        # We add a feature sink in which to store our processed features (this
        # usually takes the form of a newly created vector layer when the
        # algorithm is run in QGIS).
        self.addParameter(
            QgsProcessingParameterFileDestination(
                self.OUTPUT,
                self.tr('Output counterpart streams')
            )
        )

        return

    def processAlgorithm(self, parameters, context, feedback):
        """
        Here is where the processing itself takes place.
        """
        dem = self.parameterAsRasterLayer(parameters, self.INPUT, context).dataProvider().dataSourceUri()

        rivers = self.parameterAsVectorLayer(parameters, self.RIVERS, context).dataProvider().dataSourceUri()

        QgsMessageLog.logMessage(message=rivers)

        field = self.parameterAsFields(parameters, self.FIELD, context)[0]
        dist = self.parameterAsDouble(parameters, self.DIST, context)
        acc_mask_filter = self.parameterAsDouble(parameters, self.COST_MASK, context)
        counterpart_vectors = self.parameterAsOutputLayer(parameters, self.OUTPUT, context)

        counterpart_streams(dem, rivers, field, dist, acc_mask_filter, counterpart_vectors)

        return {self.OUTPUT: counterpart_vectors}



    def name(self):
        """
        Returns the algorithm name, used for identifying the algorithm. This
        string should be fixed for the algorithm, and must not be localised.
        The name should be unique within each provider. Names should contain
        lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'Counterpart Streams'

    def displayName(self):
        """
        Returns the translated algorithm name, which should be used for any
        user-visible display of the algorithm name.
        """
        return self.tr(self.name())

    def group(self):
        """
        Returns the name of the group this algorithm belongs to. This string
        should be localised.
        """
        return self.tr(self.groupId())

    def groupId(self):
        """
        Returns the unique ID of the group this algorithm belongs to. This
        string should be fixed for the algorithm, and must not be localised.
        The group id should be unique within each provider. Group id should
        contain lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return ''

    def tr(self, string):
        return QCoreApplication.translate('Processing', string)

    def createInstance(self):
        return CounterpartStreamsAlgorithm()

